name: Package Benchmarks

on:
  workflow_call:

permissions:
  contents: write
  deployments: write

env:
  GOPRIVATE: go.spyder.org

jobs:
  benchmark:
    name: Execute Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{secrets.REPO_RW_PAT}}

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '${{ vars.PYTHON_VERSION }}'
          check-latest: true

      - uses: actions/setup-go@v4
        with:
          go-version: $GO_VERSION

      - name: Run benchmark
        run: go test -bench=. ./... | tee output.txt

      - name: Download previous benchmark data
        uses: actions/cache@v3
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmark Results
          tool: 'go'
          output-file-path: output.txt
          benchmark-data-dir-path: dev/bench
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '${{ vars.ALERT_CC_USERS }}'
