name: Package Benchmarks

on:
  workflow_call:

env:
  GOPRIVATE: go.devnw.com,go.diver.dev,go.atomizer.io,go.secteria.com,go.structs.dev
  GO_VERSION: ${{vars.GO_VERSION}}
  GIT_CREDENTIALS: ${{secrets.GIT_CREDENTIALS}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  ALERT_CC_USERS: ${{vars.ALERT_CC_USERS}}

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Execute Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{env.GO_VERSION}}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run benchmark
        run: go test -bench=. ./... | tee output.txt
      - name: Download previous benchmark data
        uses: actions/cache@v3
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmark Results
          tool: 'go'
          output-file-path: output.txt
          benchmark-data-dir-path: dev/bench
          github-token: ${{env.GITHUB_TOKEN}}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '${{env.ALERT_CC_USERS}}'
