name: Auto-Merge Dependabot
on:
  workflow_call:
    secrets:
      GH_ACCESS_TOKEN:
        required: true 

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: runs-on=${{ github.run_id }}/runner=2cpu-linux-x64
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto "1"
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Auto approve
        run: gh pr review --approve "1"
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
