name: Update README with Go documentation

on:
  workflow_call:

env:
  GOPRIVATE: go.spyder.org


jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{secrets.REPO_RW_PAT}}

      - name: Check out repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '${{ vars.PYTHON_VERSION }}'
          check-latest: true

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ vars.GO_VERSION }}

      - name: Generate Go documentation and update README
        run: |
          go install github.com/robertkrimen/godocdown/godocdown@latest
          godocdown . > README.md

      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs(README.md): update go documentation"
          title: "Update Go documentation in README"
          body: "This PR updates the Go documentation in the README."
          branch: "update-go-documentation"
          base: "main"
          labels: "documentation,automerge"
