name: Benchmark

on:
  workflow_call:

env:
  GOPRIVATE: ${{ vars.GOPRIVATE }}

jobs:
  release:
    name: Make Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '${{ vars.PYTHON_VERSION }}'
          check-latest: true

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ vars.GO_VERSION }}

      - name: Benchmark
        run: make bench-ci

      - name: Early Exit on Empty Benchmark
        id: early-exit
        run: |
          if [ ! -e output.txt ] || [ ! -s output.txt ]; then
            echo ""
          else
            cat output.txt
          fi
      - name: Debug Benchmark Found
        run: echo "benchmarks_found is [${{ steps.early-exit.outputs.stdout }}]"

      - name: Download previous benchmark data
        if: ${{ steps.early-exit.outputs.stdout != '' }}
        uses: actions/cache@v3
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        if: ${{ steps.early-exit.outputs.stdout != '' }}
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmark Results
          tool: 'go'
          output-file-path: output.txt
          benchmark-data-dir-path: dev/bench
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '${{ vars.ALERT_CC_USERS }}'
