name: Build

on:
  workflow_call:

env:
  GOPRIVATE: go.spyder.org

jobs:
  build:
    name: Make Build
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '${{ vars.PYTHON_VERSION }}'
          check-latest: true

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ vars.GO_VERSION }}

      - name: Build
        run: make build-ci

      - name: Upload Test Coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.txt

      - name: Upload Fuzz Results
        uses: actions/upload-artifact@v3
        with:
          name: fuzz-results
          path: testdata/fuzz

  pre-release:
    name: "Pre Release"
    if: github.ref == 'refs/heads/main'
    runs-on: "ubuntu-latest"
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
