name: Make Build

on:
  workflow_call:
    secrets:
      GIT_CREDENTIALS:
        required: true
      OP_SERVICE_ACCOUNT_TOKEN:
        required: false
      GH_ACCESS_TOKEN:
        required: true
      GORELEASER_KEY:
        required: false
      TS_OAUTH_CLIENT_ID:
        required: false
      TS_OAUTH_SECRET:
        required: false
      GOPRIVATE:
        required: false
      FONTAWESOME_TOKEN:
        required: false
      CACHIX_AUTH_TOKEN:
        required: true

env:
  GOPRIVATE: ${{ vars.GOPRIVATE }}
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
  GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
  FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}

jobs:
  build:
    name: 'Build'
    runs-on: runs-on=${{ github.run_id }}/runner=2cpu-linux-x64
    steps:
      - uses: devnw/workflows/.github/actions/nix-setup@main
        with:
          git-credentials: ${{ secrets.GIT_CREDENTIALS }}
          gh-access-token: ${{ secrets.GH_ACCESS_TOKEN }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: 'Build'
        run: make build

      - name: Upload Test Coverage
        uses: actions/upload-artifact@v6
        with:
          name: coverage
          path: coverage.txt

      - name: Upload Fuzz Results
        uses: actions/upload-artifact@v6
        with:
          name: fuzz-results
          path: testdata/fuzz
