name: Benchmark

on:
  workflow_call:

env:
  GOPRIVATE: go.devnw.com,go.atomizer.io,go.codepros.org,go.spyder.org
  GO_VERSION: ${{vars.GO_VERSION}}
  GIT_CREDENTIALS: ${{secrets.GIT_CREDENTIALS}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  ALERT_CC_USERS: ${{vars.ALERT_CC_USERS}}

jobs:
  release:
    name: Make Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{env.GIT_CREDENTIALS}}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{env.GO_VERSION}}

      - name: Benchmark
        run: make bench-ci

      - name: Download previous benchmark data
        uses: actions/cache@v3
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmark Results
          tool: 'go'
          output-file-path: output.txt
          benchmark-data-dir-path: dev/bench
          github-token: ${{env.GITHUB_TOKEN}}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '${{env.ALERT_CC_USERS}}'
