name: Release

on:
  workflow_call:

env:
  GOPRIVATE: go.devnw.com,go.atomizer.io,go.codepros.org,go.spyder.org
  GH_ACCESS_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  release:
    name: Make Release
    runs-on: ubuntu-latest
    steps:
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '${{ vars.PYTHON_VERSION }}'
          check-latest: true

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ vars.GO_VERSION }}

      - name: Release
        run: make release-ci
