name: Build

on:
  workflow_call:

permissions:
  contents: write
  deployments: write

env:
  GOPRIVATE: ${{ vars.GOPRIVATE }}
  GH_ACCESS_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  lint:
    name: Lint
    uses: devnw/workflows/.github/workflows/nix.yml@main
    with:
      job: lint
      command: make lint
    secrets: inherit # pragma: allowlist secret

  build:
    name: Execute Build
    uses: devnw/workflows/.github/workflows/nix.yml@main
    with:
      job: build 
      command: make build-ci
    secrets: inherit # pragma: allowlist secret

  test:
    name: Execute Tests
    needs: [lint, build]
    uses: devnw/workflows/.github/workflows/nix.yml@main
    with:
      job: test
      command: make test-ci
    secrets: inherit # pragma: allowlist secret

  benchmark:
    name: Execute Benchmarks
    needs: [lint, build, test]
    uses: devnw/workflows/.github/workflows/nix.yml@main
    with:
      job: benchmark
      command: make bench-ci
    secrets: inherit # pragma: allowlist secret
