name: Make CI/CD

on:
  workflow_call:
    secrets:
      GIT_CREDENTIALS:
        required: true
      OP_SERVICE_ACCOUNT_TOKEN:
        required: false 
      GH_ACCESS_TOKEN:
        required: true 
      GORELEASER_KEY:
        required: false
      TS_OAUTH_CLIENT_ID:
        required: false
      TS_OAUTH_SECRET:
        required: false
      GOPRIVATE:
        required: false
      FONTAWESOME_TOKEN:
        required: false

env:
  GOPRIVATE: ${{ vars.GOPRIVATE }}
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
  GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
  FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}

permissions:
  contents: write
  deployments: write
  packages: write
  pages: write

jobs:
  build:
    name: Lint, Build, Test, Benchmark
    if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
    uses: devnw/workflows/.github/workflows/nix-lab.yml@main
    with:
      job: build
      command: make bench-ci
    secrets: inherit # pragma: allowlist secret
  release:
    name: Lint, Build, Test, Benchmark and Release
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    uses: devnw/workflows/.github/workflows/nix-lab.yml@main
    with:
      job: release
      command: make release-ci
    secrets: inherit # pragma: allowlist secret
