on:
  workflow_call:
    inputs:
      job:
        required: true
        type: string
      command:
        required: true
        type: string
      tailnet:
        required: false
        type: boolean
    secrets:
      GIT_CREDENTIALS:
        required: true
      OP_SERVICE_ACCOUNT_TOKEN:
        required: false
      GH_ACCESS_TOKEN:
        required: true
      GORELEASER_KEY:
        required: false
      TS_OAUTH_CLIENT_ID:
        required: false
      TS_OAUTH_SECRET:
        required: false
      FONTAWESOME_TOKEN:
        required: false
      DOCS_LOCATION:
        required: true
      CACHIX_AUTH_TOKEN:
        required: true
      CODECOV_TOKEN:
        required: false
      COMPASS_API_KEY:
        required: false
      COMPASS_USER:
        required: false
      COMPASS_USER_EMAIL:
        required: false
      REPO_RW_PAT:
        required: false

jobs:
  job:
    name: '${{ inputs.job }}'
    runs-on: runs-on=${{ github.run_id }}/runner=2cpu-linux-x64
    permissions:
      contents: write
      deployments: write
      packages: write
      pages: write

    env:
      GOPRIVATE: ${{ vars.GOPRIVATE }}
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
      GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
      FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
      DOCS_LOCATION: ${{ secrets.DOCS_LOCATION }}
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      COMPASS_API_KEY: ${{ secrets.COMPASS_API_KEY }}
      COMPASS_USER: ${{ secrets.COMPASS_USER }}
      COMPASS_USER_EMAIL: ${{ secrets.COMPASS_USER_EMAIL }}
      REPO_RW_PAT: ${{ secrets.REPO_RW_PAT }}

    steps:
      - uses: devnw/workflows/.github/actions/nix-setup@main
        with:
          git-credentials: ${{ secrets.GIT_CREDENTIALS }}
          gh-access-token: ${{ secrets.GH_ACCESS_TOKEN }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Tailscale
        if: ${{ inputs.tailnet }}
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run Command
        run: ${{ inputs.command }}

      - name: Upload Test Coverage
        uses: actions/upload-artifact@v5
        with:
          if-no-files-found: ignore
          name: coverage
          path: coverage.txt

      - name: Upload Fuzz Results
        uses: actions/upload-artifact@v5
        with:
          if-no-files-found: ignore
          name: fuzz-results
          path: testdata/fuzz

      - name: Upload Test Coverage
        uses: actions/upload-artifact@v5
        with:
          if-no-files-found: ignore
          name: benchmarks
          path: bench-output.txt
